apiVersion: v1
kind: Secret
metadata:
  name: yandex-object-storage-secret
  namespace: kube-system
type: Opaque
stringData:
  accessKeyID: 
  secretAccessKey: 
  endpoint: https://storage.yandexcloud.net
