apiVersion: v1
kind: Pod
metadata:
  name: nginx-debug-3
spec:
  shareProcessNamespace: true
  containers:
    - name: nginx
      image: kyos0109/nginx-distroless:latest
      ports:
        - containerPort: 80
    - name: debugger
      image: ubuntu
      command:
        - sleep
        - "3600"
      stdin: true
      tty: true
