repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: kafka-prod
    namespace: prod
    chart: bitnami/kafka
    version: 32.2.8
    values:
      - values-prod.yaml

  - name: kafka-dev
    namespace: dev
    chart: bitnami/kafka
    values:
      - values-dev.yaml

