apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-metrics
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: nginx-metrics
  endpoints:
    - port: metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default

