apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-metrics
  template:
    metadata:
      labels:
        app: nginx-metrics
    spec:
      containers:
      - name: nginx
        image: custom-nginx-metrics:v2
        ports:
        - containerPort: 80
        - containerPort: 9113
      - name: exporter
        image: nginx/nginx-prometheus-exporter:latest
        args:
          - -nginx.scrape-uri=http://localhost/nginx_status
        ports:
        - containerPort: 9113

