apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
rules:
- nonResourceURLs: ["/metrics", "/metrics/cadvisor", "/metrics/resource"]
  verbs: ["get"]

- apiGroups: [""]
  resources: ["nodes/metrics", "nodes/stats", "pods/metrics"]
  verbs: ["get", "list"]

- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
