apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-minikube-hostpath
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: false
