global:
  name: consul
  datacenter: dc1
  enabled: true

server:
  replicas: 3
  bootstrapExpect: 3
  disruptionBudget:
    maxUnavailable: 1

ui:
  enabled: true

connectInject:
  enabled: false

controller:
  enabled: false

client:
  enabled: true
