apiVersion: v1
kind: Pod
metadata:
  name: vault-debug
  namespace: vault
spec:
  containers:
    - name: debug
      image: ubuntu:22.04
      command: ["/bin/bash"]
      args: ["-c", "sleep infinity"]
      securityContext:
        runAsUser: 0  # root
      volumeMounts:
        - name: tools
          mountPath: /tools
  volumes:
    - name: tools
      emptyDir: {}

  restartPolicy: Never

