apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuber-pvc
spec:
  storageClassName: "my-minikube-hostpath"
  #storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
