auth_enabled: false

loki:
  storage:
    type: s3
    s3:
      endpoint: s3.storage.yandexcloud.net
      bucketnames: loki-logs-bucket
      access_key_id: 
      secret_access_key: 
      s3forcepathstyle: true

  commonConfig:
    replication_factor: 1

  schemaConfig:
    configs:
      - from: 2023-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h

  nodeSelector:
    purpose: infra

  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"

singleBinary:
  replicas: 1

ingress:
  enabled: false

